# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 13:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('mobile', models.CharField(max_length=12, null=True, unique=True)),
                ('mobile_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_verified',
        ),
        migrations.AddField(
            model_name='wechataccount',
            name='origin_user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='wechat_account_origin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileaccount',
            name='origin_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_account_origin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobileaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
