# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
