# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-01 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171101_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQAccount',
            fields=[
                ('weibo_open_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WechatAccount',
            fields=[
                ('wechat_open_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('wechat_unionid', models.CharField(default=' ', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WeiboAccount',
            fields=[
                ('weibo_open_id', models.CharField(max_length=190, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'validated'), ('no', 'invalidated')], default=1),
        ),
        migrations.AddField(
            model_name='weiboaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weibo_account', to='user.User'),
        ),
        migrations.AddField(
            model_name='wechataccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_account', to='user.User'),
        ),
        migrations.AddField(
            model_name='qqaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_account', to='user.User'),
        ),
    ]
