# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20171104_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wechataccount',
            old_name='sessionkey',
            new_name='session_key',
        ),
    ]
