# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171104_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=time.time, null=True),
        ),
    ]
